version: '3.8'
services:
  # data_collector:
  #   build:
  #     context: ./
  #   volumes:
  #     - ./data:/opt/growatt_dashboard/data

  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - 4000:3000
    volumes:
      - './grafana_config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml'
      - './grafana_config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml'
      - './grafana_config/dashboards/dashboard.json:/app/dashboards/dashboard.json'
      - './grafana_config/grafana.ini:/etc/grafana/grafana.ini'
      - './data:/app/data'
    environment:
      # - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource, grafana-piechart-panel, https://github.com/yesoreyeram/yesoreyeram-boomtable-panel/releases/download/v1.5.0-alpha.3/yesoreyeram-boomtable-panel-1.5.0-alpha.3.zip;yesoreyeram-boomtable-panel, grafana-influxdb-flux-datasource, fetzerch-sunandmoon-datasource, simpod-json-datasource

